apiVersion: apps/v1
kind: Deployment
metadata:
  name: <DEPLOYMENT_NAME>
  labels:
    app: bodyshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bodyshop-service
  template:
    metadata:
      labels:
        app: bodyshop-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: bodyshop
        image: registry.gitlab.com/golang-developer-cloudmts_main/team201/bodyshop:main
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: bodyshop-service
spec:
  selector:
    app: bodyshop-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002